

#         Powered by TabooLib 6.2         #


Settings:
  # 数据库
  database:
    host: localhost
    port: 3306
    user: minecraft
    password: password
    database: minecraft
  admin:
    - 1747484670
    - 3332366064
    - 3186320035